# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## neoforge
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.15
minecraft_version=1.21.5
minecraft_version_range=[1.21.5]
neo_version=21.5.66-beta
neo_version_range=[21.5.65,)
loader_version_range=[4,)

## Mod Properties
mod_name=Shutter
mod_id=shutter
mod_version=2.1.7-neoforge-1.21
mod_group_id=net.stehschnitzel.shutter
mod_authors=Stehschnitzel
mod_description=Adds Shutters for minecraft and different mods
mod_license=https://github.com/nudelauflauch/shutter/blob/main/LICENSE.md