org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17


minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
neo_version_range=[21.1.0,)
loader_version_range=[1,)

jei_version = 19.9.1.125

## Mod Properties
mod_name=Shutter
mod_id=shutter
mod_version=2.3.0-neoforge-1.21.1
mod_group_id=net.stehschnitzel.shutter
mod_authors=Stehschnitzel
mod_description=Adds Shutters for minecraft and different mods
mod_license=https://github.com/nudelauflauch/shutter/blob/main/LICENSE.md